# Change these first
owner: Blue-Fin-Ryan-Cunningham # Your GitHub username
repo: Blue-Fin-Ryan-Cunningham/BlueFinAPIs-UppTime # Repository name

sites:
  - name: ITS API
    url: https://itsbackofficeapi.azurewebsites.net/swagger/index.html
  - name: ITS Token Service
    url: https://its-tokenserviceapi.azurewebsites.net/.well-known/openid-configuration
  - name: ITS Public API
    url: https://its-public-web-api-live.azurewebsites.net/swagger/index.html

status-website:
  baseUrl: /BlueFinAPIs-UppTime  # Ensure correct base URL for GitHub Pages
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**TESTING** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Optional: Add a Content Security Policy in GitHub Pages (_headers file required)
static:
  _headers: |
    /  
      Content-Security-Policy: default-src 'self'; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com;
